# Generated by Django 6.0.4 on 2026-04-10 12:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("stock", "Stock"),
                            ("crypto", "Crypto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("symbol", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=120)),
                (
                    "buy_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                ("purchase_date", models.DateField()),
                (
                    "current_price_cache",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                ("price_currency", models.CharField(default="USD", max_length=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-purchase_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketPriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("stock", "Stock"),
                            ("crypto", "Crypto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("symbol", models.CharField(max_length=40)),
                ("price", models.DecimalField(decimal_places=2, max_digits=16)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("source", models.CharField(max_length=40)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
    ]
