# Generated by Django 6.0.4 on 2026-04-10 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("investments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="marketpricesnapshot",
            index=models.Index(
                fields=["symbol", "asset_type", "captured_at"],
                name="investments_symbol_921e52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["user", "asset_type", "symbol"],
                name="investments_user_id_f2b5c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["symbol", "asset_type"], name="investments_symbol_83c3c6_idx"
            ),
        ),
    ]
