# Generated by Django 6.0.4 on 2026-04-10 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="stripe_payment_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="provider",
            field=models.CharField(choices=[("stripe", "Stripe")], max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")], max_length=10
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["stripe_payment_id"], name="transaction_stripe__d18bcb_idx"
            ),
        ),
    ]
