# Generated by Django 6.0.4 on 2026-04-10 12:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "reliability_factor",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("max_tenure_months", models.PositiveIntegerField(default=60)),
                ("active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["interest_rate", "-reliability_factor"],
                "indexes": [
                    models.Index(
                        fields=["active", "interest_rate"],
                        name="loans_loanp_active_318fc7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eligible_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("emi", models.DecimalField(decimal_places=2, max_digits=14)),
                ("tenure_months", models.PositiveIntegerField()),
                ("trust_score", models.PositiveSmallIntegerField()),
                ("status", models.CharField(default="eligible", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="loans.loanprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-trust_score", "emi"],
            },
        ),
    ]
