# Generated by Django 6.0.4 on 2026-04-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_loanprovider_created_by_loanapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="salary_slip_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
