# Generated by Django 6.0.4 on 2026-04-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("monthly_expense", "Monthly Expense"),
                    ("profit_loss", "Profit Loss"),
                    ("loan_warning", "Loan Warning"),
                    ("payment_request", "Payment Request"),
                ],
                max_length=40,
            ),
        ),
    ]
